### PR TITLE
Fix attribute reloading

### PR DESCRIPTION
**Pull request by wencke-lm**
r? @TimDiekmann Better look at it carefully. I just did what suited my purposes best. We have to make sure that I did not destroy other things in the process 😇 
Do we want to put the code that sets the target and verifies that the receiver is logged in a function or method? Any suggestions?
That's basically the same 6 times now.

### CODE REVIEW

**Comment by TimDiekmann** [comment]
At first glance, the code looks good.

> Do we want to put the code that sets the target and verifies that the receiver is logged in a function or method?

We can simplify the code to something like this:
```python
    @blp.query("room", RoomSchema, check_etag=False)
    @blp.query("receiver", UserSchema, check_etag=False)
    # ...
    def post(self, *, room, receiver, id, **kwargs):
        if receiver is not None:
            target = receiver.session_id
            if target is None:
                abort(
                    HTTPStatus.UNPROCESSABLE_ENTITY,
                    query={
                        "receiver_id": f"User `{receiver.id}` does not have a session id associated"
                    },
                )
        else:
            target = str(room.id)

        kwargs["id"] = id
        Log.add("...", room=room, receiver=receiver, data=kwargs)
        socketio.emit("...", kwargs, room=target)
        return kwargs
```

Then, the logic can be moved out to another function:
```python
    def get_target(receiver, fallback):
        if receiver is not None:
            target = receiver.session_id
            if target is None:
                abort(
                    HTTPStatus.UNPROCESSABLE_ENTITY,
                    query={
                        "receiver_id": f"User `{receiver.id}` does not have a session id associated"
                    },
                )
        else:
            target = fallback
        return target
```

**Comment by wencke-lm** [comment]
Wouldn't this make the receiver an obligatory argument? As its no longer passed with the json but as part of the url? Or can we do this while keeping the receiver as part of json?

**Comment by TimDiekmann** [comment]
`Blueprint.query` uses the `kwargs` argument to get the parameter: https://github.com/clp-research/slurk/blob/9913a377d468537c804e2326b8edce27deb9a9e8/slurk/extensions/api.py#L136
Maybe the decorator order has to be shuffled a bit but I thing this would work.

**Comment by wencke-lm** [comment]
I see 👍 Will try this.

**Comment by TimDiekmann** [comment]
In either case, the main logic for getting the target can easily be moved out to another function. 👍🏻

**Comment by wencke-lm** [comment]
```
    @wraps(func)
    def wrapper(*args, **kwargs):
        parameter_id = f"{parameter}_id"
>       id = kwargs.pop(parameter_id)
E       KeyError: 'receiver_id
``` 
As I suspected, the query decorator assumes the existence of a paramter. That's why it has only been used where this was enforced due to the paramter being part of the url. Anyway, I simply put the receiver retrieval also into the function.

**Pull request merged**
